apiVersion: apps/v1
kind: Deployment
metadata:
  name: __name__
  labels:
    app: busybox
    layer: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      volumes:
      containers:
        - name: busybox
          image: busybox
          command:
            - sleep
            - __sleep__
